# Copyright 2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

rules:
  cache-poisoning:
    ignore:
      # This job do not release any artifact, we do not care about cache poisoning
      - matrix-tools.yml:33
      # This job do not release any artifact, we do not care about cache poisoning
      - matrix-tools.yml:56
      # This job do not release any artifact, we do not care about cache poisoning
      - releasing.yml:30
      # This job do not release any artifact, we do not care about cache poisoning
      - releasing.yml:79
      # This job do not release any artifact, we do not care about cache poisoning
      - releasing.yml:176
      # We disable cache on releases
      - releasing.yml:33
      # This job do not release any artifact, we do not care about cache poisoning
      - packages.yml:40
      # We disable cache on releases
      - packages.yml:85
      # This job do not release any artifact, we do not care about cache poisoning
      - packages.yml:145

