{{- /*
Copyright 2025 New Vector Ltd
Copyright 2025 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with .Values.matrixAuthenticationService -}}
{{- if .enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "element-io.matrix-authentication-service.configmap-name" (dict "root" $ "context"  (dict "isHook" false)) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.matrix-authentication-service.labels" (dict "root" $ "context" .) | nindent 4 }}
data:
  {{- include "element-io.matrix-authentication-service.configmap-data" (dict "root" $ "context" .) | nindent 2 -}}
{{ end -}}
{{- end -}}
