# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

ess:
  serverName: ess.localhost

defaultMatrixServer:
  baseUrl: https://synapse.ess.localhost

ingress:
  host: element.ess.localhost
