# Copyright 2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

"""
Pytest tests for user prompts in the migration script.
Tests for missing secrets and extra files handling.
"""

import asyncio
import base64
import logging

import pytest

from ..engine import MigrationEngine
from ..inputs import InputProcessor


def test_migration_with_missing_secrets_prompt(
    caplog, monkeypatch, tmp_path, synapse_config_with_signing_key, write_synapse_config
):
    """Test migration workflow that prompts for missing secrets with timeout."""
    # Create Synapse configuration with missing secrets
    synapse_config = synapse_config_with_signing_key.copy()
    # Remove password to simulate missing secret
    del synapse_config["database"]["args"]["password"]
    # Remove other secrets to simulate missing secrets
    del synapse_config["macaroon_secret_key"]
    del synapse_config["registration_shared_secret"]

    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config)
    # Load migration input - this should prompt for missing secrets
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )
    ess_values = {}

    pretty_logger = logging.getLogger("test_prompts")
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler())

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Mock user input for missing secrets
    side_effect = (n for n in ("test_db_password", "test_macaroon", "test_registration"))
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        nonlocal ess_values
        ess_values = engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))
        # Capture the output after the test runs
        output = caplog.text

        # Verify that warnings about generated secrets are present
        assert "SECRETS REQUIRED FOR MIGRATION" in output
        assert "Synapse database password" in output
        assert "Synapse macaroon secret" in output
        assert "✅ All required SYNAPSE secrets have been provided" in output

        # Verify that secrets were handled
        synapse_config_result = ess_values["synapse"]

        # Check that serverName is present at the top level of ess_values (camelCase for Helm values)
        assert "serverName" in ess_values
        assert ess_values["serverName"] == "test.example.com"

        # Check that credential schema was used for required secrets
        # Only macaroon has init_if_missing_from_source_cfg=False in this test
        assert "macaroon" in synapse_config_result

        # Verify that Secrets were generated
        assert len(engine.secrets) > 0
        for secret in engine.secrets:
            assert "synapse.postgres.password" in secret.data
            assert base64.b64decode(secret.data["synapse.postgres.password"]) == b"test_db_password"
            assert "synapse.macaroon" in secret.data
            assert base64.b64decode(secret.data["synapse.macaroon"]) == b"test_macaroon"
            # registration shared secret is accepted to be generated by init secrets
            assert "synapse.registrationSharedSecret" not in secret.data
    except asyncio.TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        # If the test fails, it should be a meaningful failure
        # not a timeout or input issue
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            # Re-raise the original exception
            raise


def test_migration_with_unknown_workers_prompt(
    caplog,
    monkeypatch,
    tmp_path,
    synapse_config_with_signing_key,
    synapse_config_with_instance_map,
    write_synapse_config,
):
    """Test migration workflow that prompts for missing secrets with timeout."""

    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key | synapse_config_with_instance_map)

    # Load migration input - this should prompt for missing secrets
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )
    ess_values = {}

    pretty_logger = logging.getLogger("test_prompts")
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler())

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Mock user input for missing secrets
    side_effect = (n for n in ("8"))
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        nonlocal ess_values
        ess_values = engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))
        # Capture the output after the test runs
        output = caplog.text

        # Verify that warnings about generated secrets are present
        assert " No worker type found for instance funny-name" in output

        # Verify that secrets were handled
        synapse_config_result = ess_values["synapse"]

        assert "workers" in synapse_config_result
        assert len(synapse_config_result["workers"]) == 2
        assert "event-creator" in synapse_config_result["workers"]
        assert "synchrotron" in synapse_config_result["workers"]

    except asyncio.TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        # If the test fails, it should be a meaningful failure
        # not a timeout or input issue
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            # Re-raise the original exception
            raise
