# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

ess:
  serverName: ess.localhost

synapse:
  enabled: true
  registrationSharedSecret:
    secret: ess-secrets
    secretKey: registrationSharedSecret
  macaroon:
    secret: ess-secrets
    secretKey: macaroon
  signingKey:
    secret: ess-secrets
    secretKey: signingKey

  postgres:
    host: synapse-postgresql
    user: synapse_user
    database: synapse_db
    password:
      secret: synapse-postgres-db
      secretKey: password

  ingress:
    host: synapse.ess.localhost
    tlsSecret: synapse-web-tls

  tolerations:
    - key: context
      operator: Equal
      value: pytest
      effect: NoSchedule

  workers:
    sliding-sync:
      enabled: true
    media-repository:
      enabled: true

  haproxy:
    replicas: 1
    tolerations:
      - key: context
        operator: Equal
        value: pytest
        effect: NoSchedule

  redis:
    tolerations:
      - key: context
        operator: Equal
        value: pytest
        effect: NoSchedule

elementWeb:
  enabled: false
