# Copyright 2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

"""
Pytest tests for user prompts in the migration script.
Tests for missing secrets and extra files handling.
"""

import asyncio
import base64
import logging
import shutil
from io import StringIO

import pytest
from ess_migration_tool.engine import MigrationEngine
from ess_migration_tool.extra_files import ExtraFilesError
from ess_migration_tool.inputs import InputProcessor
from ess_migration_tool.secrets import SecretsError
from ess_migration_tool.synapse import prompt_for_ingress_host


def test_migration_with_missing_secrets_prompt(
    monkeypatch, tmp_path, synapse_config_with_signing_key, write_synapse_config
):
    """Test migration workflow that prompts for missing secrets with timeout."""
    # Create Synapse configuration with missing secrets
    synapse_config = synapse_config_with_signing_key.copy()
    # Remove password to simulate missing secret
    del synapse_config["database"]["args"]["password"]
    # Remove other secrets to simulate missing secrets
    del synapse_config["macaroon_secret_key"]
    del synapse_config["registration_shared_secret"]

    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config)
    # Load migration input - this should prompt for missing secrets
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )
    ess_values = {}

    log_capture_string = StringIO()
    pretty_logger = logging.getLogger(test_migration_with_missing_secrets_prompt.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Set database mode directly
    engine.global_options.use_existing_database = True

    # Mock user input for missing secrets
    side_effect = (n for n in ("test_db_password", "test_macaroon", "test_registration"))
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        nonlocal ess_values
        ess_values = engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))
        # Capture the output after the test runs
        output = log_capture_string.getvalue()

        # Verify that warnings about generated secrets are present
        assert "SECRETS REQUIRED FOR MIGRATION" in output
        assert "Synapse database password" in output
        assert "Synapse macaroon secret" in output
        assert "✅ All required SYNAPSE secrets have been provided" in output

        # Verify that secrets were handled
        synapse_config_result = ess_values["synapse"]

        # Check that serverName is present at the top level of ess_values (camelCase for Helm values)
        assert "serverName" in ess_values
        assert ess_values["serverName"] == "test.example.com"

        # Check that credential schema was used for required secrets
        # Only macaroon has init_if_missing_from_source_cfg=False in this test
        assert "macaroon" in synapse_config_result

        # Verify that Secrets were generated
        assert len(engine.secrets) > 0
        for secret in engine.secrets:
            assert "synapse.postgres.password" in secret.data
            assert base64.b64decode(secret.data["synapse.postgres.password"]) == b"test_db_password"
            assert "synapse.macaroon" in secret.data
            assert base64.b64decode(secret.data["synapse.macaroon"]) == b"test_macaroon"
            # registration shared secret is accepted to be generated by init secrets
            assert "synapse.registrationSharedSecret" not in secret.data
    except TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        # If the test fails, it should be a meaningful failure
        # not a timeout or input issue
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            # Re-raise the original exception
            raise
    finally:
        log_capture_string.close()


def test_prompt_for_ingress_host_with_missing_public_baseurl(monkeypatch):
    """Test that missing public_baseurl triggers user prompt for ingress host."""
    pretty_logger = logging.getLogger(test_prompt_for_ingress_host_with_missing_public_baseurl.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)

    log_capture_string = StringIO()
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    # Mock user input using monkeypatch
    monkeypatch.setattr("builtins.input", lambda _: "matrix.example.com")

    try:
        # Test with missing public_baseurl
        result = prompt_for_ingress_host(pretty_logger, None)

        # Verify the result
        assert result == "matrix.example.com"

        # Verify prompt messages were shown
        output = log_capture_string.getvalue()
        assert "❌ Synapse public_baseurl not found in configuration" in output
        assert "The chart requires Synapse Public BaseURL to be distinct from the server name" in output
        assert "Please provide Synapse ingress host (e.g., matrix.example.com):" in output

    finally:
        log_capture_string.close()


def test_quiet_mode_fails_on_missing_secrets(tmp_path, synapse_config_with_signing_key, write_synapse_config):
    """Test that migration fails in quiet mode when secrets are missing."""
    # Create Synapse configuration with missing secrets
    synapse_config = synapse_config_with_signing_key.copy()
    # Remove password to simulate missing secret
    del synapse_config["database"]["args"]["password"]
    del synapse_config["macaroon_secret_key"]

    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config)

    # Load migration input
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )

    # Create logger in quiet mode (CRITICAL level)
    pretty_logger = logging.getLogger(test_quiet_mode_fails_on_missing_secrets.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.CRITICAL)  # This simulates --quiet mode
    pretty_logger.addHandler(logging.StreamHandler())

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Set database mode directly to avoid prompting (simulate --database-mode existing)
    engine.global_options.use_existing_database = True

    # Test that it raises SecretsError in quiet mode
    with pytest.raises(SecretsError) as exc_info:
        engine.run_migration()

    # Verify the error message
    assert "quiet mode" in str(exc_info.value)
    assert "Cannot prompt for secrets when --quiet is enabled" in str(exc_info.value)
    assert "synapse.postgres.password" in str(exc_info.value)


def test_quiet_mode_fails_on_missing_extra_files(
    tmp_path, synapse_config_with_signing_key, synapse_config_with_email_templates, write_synapse_config
):
    """Test that migration fails in quiet mode when extra files are missing."""
    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key | synapse_config_with_email_templates)

    # Remove the email templates directory to simulate missing files
    shutil.rmtree(tmp_path / "email_templates")

    # Load migration input
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )

    # Create logger in quiet mode (CRITICAL level)
    pretty_logger = logging.getLogger(test_quiet_mode_fails_on_missing_extra_files.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.CRITICAL)  # This simulates --quiet mode
    pretty_logger.addHandler(logging.StreamHandler())

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Set database mode directly to avoid prompting (simulate --database-mode existing)
    engine.global_options.use_existing_database = True

    # Test that it raises ExtraFilesError in quiet mode
    with pytest.raises(ExtraFilesError) as exc_info:
        engine.run_migration()

    # Verify the error message
    assert "quiet mode" in str(exc_info.value)
    assert "Cannot prompt for files when --quiet is enabled" in str(exc_info.value)


def test_migration_with_unknown_workers_prompt(
    monkeypatch,
    tmp_path,
    synapse_config_with_signing_key,
    synapse_config_with_instance_map,
    write_synapse_config,
):
    """Test migration workflow that prompts for missing secrets with timeout."""

    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key | synapse_config_with_instance_map)
    # Load migration input - this should prompt for missing secrets
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )
    ess_values = {}

    log_capture_string = StringIO()
    pretty_logger = logging.getLogger(test_migration_with_unknown_workers_prompt.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Set database mode directly
    engine.global_options.use_existing_database = True

    # Mock user input for workers
    side_effect = (n for n in ("8",))
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        nonlocal ess_values
        ess_values = engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))
        # Capture the output after the test runs
        output = log_capture_string.getvalue()
        assert " No worker type found for instance funny-name" in output

        # Verify that secrets were handled
        synapse_config_result = ess_values["synapse"]

        assert "workers" in synapse_config_result
        assert len(synapse_config_result["workers"]) == 2
        assert "event-creator" in synapse_config_result["workers"]
        assert "synchrotron" in synapse_config_result["workers"]
        assert synapse_config_result["workers"]["synchrotron"]["replicas"] == 2
    except TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        # If the test fails, it should be a meaningful failure
        # not a timeout or input issue
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            # Re-raise the original exception
            raise
    finally:
        log_capture_string.close()


def test_migration_with_missing_extra_files_prompt(
    monkeypatch,
    tmp_path,
    synapse_config_with_signing_key,
    synapse_config_with_email_templates,
    write_synapse_config,
):
    """Test migration workflow that prompts for missing secrets with timeout."""
    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key | synapse_config_with_email_templates)
    # Load migration input - this should prompt for missing secrets
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )
    ess_values = {}

    shutil.move(tmp_path / "email_templates", tmp_path / "moved")

    log_capture_string = StringIO()
    pretty_logger = logging.getLogger(test_migration_with_missing_extra_files_prompt.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Set database mode directly
    engine.global_options.use_existing_database = True

    # Mock user input for extra files discovery
    side_effect = (n for n in ("3", str(tmp_path / "moved")))
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        nonlocal ess_values
        ess_values = engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))
        # Capture the output after the test runs
        output = log_capture_string.getvalue()

        # Verify that warnings about generated secrets are present
        assert "📁 EXTRA FILES DISCOVERY" in output
        assert "The following extra files were referenced in your configuration" in output
        assert "   ⚠️  Skipping missing files..." not in output
        assert f"   ✅ Found 2 matching files in {(str(tmp_path / 'moved'))}" in output

        # Verify that extra files were handled
        synapse_config = ess_values["synapse"]
        assert len(synapse_config["extraVolumeMounts"]) == 2

    except TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        # If the test fails, it should be a meaningful failure
        # not a timeout or input issue
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            # Re-raise the original exception
            raise
    finally:
        log_capture_string.close()


def test_database_choice_prompt_existing_database(
    monkeypatch,
    tmp_path,
    synapse_config_with_signing_key,
    write_synapse_config,
):
    """Test database choice prompt when user selects existing database."""
    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key)

    # Load migration input
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )

    log_capture_string = StringIO()
    pretty_logger = logging.getLogger(test_database_choice_prompt_existing_database.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Mock user input for database choice (select option 1 - existing database)
    side_effect = (n for n in ("1",))  # Just database choice, no missing secrets
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test database choice prompt directly
    from ess_migration_tool.utils import prompt_for_database_choice

    engine.global_options.use_existing_database = prompt_for_database_choice(pretty_logger)

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))

        # Capture the output after the test runs
        output = log_capture_string.getvalue()

        # Verify database choice prompt was shown
        assert "🗃️  DATABASE CONFIGURATION CHOICE" in output
        assert "How would you like to handle the database for your ESS deployment?" in output
        assert "1. 🔗 Connect to existing database" in output
        assert "2. 🆕 Install Postgres with ESS and import database later" in output
        assert "   ✅ Using existing database configuration" in output

        # Verify that the global option was set correctly
        assert engine.global_options.use_existing_database is True

    except TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            raise
    finally:
        log_capture_string.close()


def test_database_choice_prompt_ess_managed(
    monkeypatch,
    tmp_path,
    synapse_config_with_signing_key,
    write_synapse_config,
):
    """Test database choice prompt when user selects ESS-managed Postgres."""
    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key)

    # Load migration input
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )

    log_capture_string = StringIO()
    pretty_logger = logging.getLogger(test_database_choice_prompt_ess_managed.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Mock user input for database choice (select option 2 - ESS-managed Postgres)
    side_effect = (n for n in ("2",))  # Just database choice, no missing secrets
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test database choice prompt directly
    from ess_migration_tool.utils import prompt_for_database_choice

    engine.global_options.use_existing_database = prompt_for_database_choice(pretty_logger)

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))

        # Capture the output after the test runs
        output = log_capture_string.getvalue()

        # Verify database choice prompt was shown
        assert "🗃️  DATABASE CONFIGURATION CHOICE" in output
        assert "How would you like to handle the database for your ESS deployment?" in output
        assert "1. 🔗 Connect to existing database" in output
        assert "2. 🆕 Install Postgres with ESS and import database later" in output
        assert "   ✅ Using ESS-managed Postgres (import database later)" in output

        # Verify that the global option was set correctly
        assert engine.global_options.use_existing_database is False

    except TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            raise
    finally:
        log_capture_string.close()


def test_database_choice_prompt_default(
    monkeypatch,
    tmp_path,
    synapse_config_with_signing_key,
    write_synapse_config,
):
    """Test database choice prompt when user presses Enter (default choice)."""
    # Write Synapse config
    synapse_config_file = write_synapse_config(synapse_config_with_signing_key)

    # Load migration input
    input_processor = InputProcessor()
    input_processor.load_migration_input(
        config_path=str(synapse_config_file),
        name="synapse",
    )

    log_capture_string = StringIO()
    pretty_logger = logging.getLogger(test_database_choice_prompt_default.__name__)
    pretty_logger.propagate = False
    pretty_logger.setLevel(logging.INFO)
    pretty_logger.addHandler(logging.StreamHandler(log_capture_string))

    engine = MigrationEngine(input_processor, pretty_logger=pretty_logger)

    # Mock user input for database choice (press Enter for default - option 1)
    side_effect = (n for n in ("",))  # Empty string for default choice
    monkeypatch.setattr("builtins.input", lambda _: next(side_effect))

    # Test database choice prompt directly
    from ess_migration_tool.utils import prompt_for_database_choice

    engine.global_options.use_existing_database = prompt_for_database_choice(pretty_logger)

    # Test with async timeout to prevent hanging
    async def test_with_timeout():
        engine.run_migration()

    # Run the async test with timeout
    try:
        asyncio.run(asyncio.wait_for(test_with_timeout(), timeout=10.0))

        # Capture the output after the test runs
        output = log_capture_string.getvalue()

        # Verify database choice prompt was shown
        assert "🗃️  DATABASE CONFIGURATION CHOICE" in output
        assert "   ✅ Using existing database configuration" in output

        # Verify that the global option was set to default (True - existing database)
        assert engine.global_options.use_existing_database is True

    except TimeoutError:
        pytest.fail("Test timed out - prompt may be hanging")
    except Exception as e:
        if "TimeoutError" in str(e) or "asyncio" in str(e):
            pytest.fail(f"Async test failed: {e}")
        else:
            raise
    finally:
        log_capture_string.close()
