# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

{{- with $.Values.synapse }}
{{- if .enabled }}
{{- if (include "element-io.synapse.enabledWorkers" $) | fromJson }}
{{- if .redis.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "element-io.synapse.redis.labels" $ | nindent 4 }}
  name: {{ include "element-io.synapse.redis.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
