{{- /*
Copyright 2025 New Vector Ltd
Copyright 2025 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with .Values.synapse -}}
{{- if and .enabled (or .checkConfigHook.enabled
                        (and $.Values.matrixAuthenticationService.enabled
                            $.Values.matrixAuthenticationService.syn2mas.enabled)) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "element-io.synapse-check-config.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ include "element-io.synapse.secret-name" (dict "root" $ "context" (dict "isHook" true)) }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
{{- include "element-io.synapse.secret-data"  (dict "root" $ "context" .) -}}
{{- end -}}
{{- end -}}
