# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

initSecrets:
  annotations:
    has-no-service-monitor: "true"

  podSecurityContext:
    runAsGroup: 0
