# Copyright 2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  appserviceRegistration:
    value: |
      id: matrix-rtc-authorisation-service
      as_token: "CHANGEME-Ahng4ohYaeW5Iepho8eequoh5ahthee0"
      hs_token: "CHANGEME-uu6ohbee9Eeth9ahcoh1Neiph4aiZoox"
      sender_localpart: _lk_jwt_service
      namespaces:
        users:
          - regex: ".*"
            exclusive: false
      url: null
      io.element.msc4502.scopes:
        - "urn:matrix:client:io.element.msc4502:rooms:is_joined"
      io.element.msc4512.proxy_prefix: rtc/livekit
      io.element.msc4512.proxy_url: "http://matrix-rtc-authorisation-service:8080"
