
# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  livekitAuth:
    key: CHANGEME-oolahd9xooshohSh5IeQu1natheur1oo
    secret:
      secret: "{{ $.Release.Name }}-matrix-rtc-external"
      secretKey: livekitSecret
