# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixAuthenticationService:
  additional:
    example-value:
      configSecret: "{{ $.Release.Name }}-mas-external"
      configSecretKey: config