# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

postgres:
  enabled: true

  adminPassword:
    secret: "{{ $.Release.Name }}-pg-external"
    secretKey: adminPasswordShared
