# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

elementWeb:
  enabled: true

matrixAuthenticationService:
  enabled: true

synapse:
  enabled: true

wellKnownDelegation:
  enabled: true
