# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

deploymentMarkers:
  enabled: true

elementAdmin:
  enabled: true

elementWeb:
  enabled: true

matrixAuthenticationService:
  enabled: true

matrixRTC:
  enabled: true

synapse:
  enabled: true

wellKnownDelegation:
  enabled: true
