# Copyright 2024-2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

elementAdmin:
  ingress:
    host: admin.your.tld
elementWeb:
  ingress:
    host: chat.your.tld
matrixAuthenticationService:
  ingress:
    host: account.your.tld
matrixRTC:
  ingress:
    host: mrtc.your.tld
serverName: your.tld
synapse:
  ingress:
    host: matrix.your.tld
