# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  ingress:
    additionalPaths:
    - path: /_matrix/identity
      availability: only_externally
      service:
        name: sydent
        port:
          number: 8080

    - path: /_synapse
      availability: blocked

    - path: /other
      availability: internally_and_externally
      service:
        name: something
        port:
          name: http
