# Copyright 2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  postgres:
    host:
      secret: "{{ $.Release.Name }}-synapse-external"
      secretKey: postgresHost
    user:
      secret: "{{ $.Release.Name }}-synapse-external"
      secretKey: postgresUser
    database:
      secret: "{{ $.Release.Name }}-synapse-external"
      secretKey: postgresDatabase
    port:
      secret: "{{ $.Release.Name }}-synapse-external"
      secretKey: postgresPort
