# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  registrationSharedSecret:
    secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: registrationSharedSecret
  macaroon:
    secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: macaroon
  signingKey:
    secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: signingKey

  appservices:
  - secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: bridge_registration.yaml
