# Copyright 2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  serviceMonitors:
    relabelings:
      - targetLabel: test_label
        action: replace
        replacement: test value
