# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  registrationSharedSecret:
    secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: registrationSharedSecret
  macaroon:
    secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: macaroon
  signingKey:
    secret: "{{ $.Release.Name }}-synapse-external"
    secretKey: signingKey
