# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

global:
  baseDomain: ess.localhost

# To check that templating works against the ingress
serverName: "{{ $.Values.global.baseDomain }}"

wellKnownDelegation:
  baseDomainRedirect:
   url: "https://redirect.localhost/path"
