# Copyright 2024-2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Scripts linting

on:
  pull_request:
  push:
    branches:
    - main
    - 'maintenance/*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a  # v7
      with:
        enable-cache: true
        activate-environment: true
        python-version: ${{ matrix.python-version }}

    - name: Set up UV environment
      run: uv sync --all-packages

    - name: Run ruff check
      run: |
        ruff check

    - name: Run ruff format
      run: |
        ruff format --check

    - name: mypy
      run: |
        mypy packages/ess-migration-tool

    - name: pytest packages
      run: |
        pytest packages


  cspell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      with:
        persist-credentials: false

    - uses: streetsidesoftware/cspell-action@9cd41bb518a24fefdafd9880cbab8f0ceba04d28  # v8
